import type { Metadata } from "next";
import { Nunito_Sans, Darker_Grotesque } from "next/font/google";
import "./globals.css";
import Header from "../components/Layout/Header";

const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-nunito-sans",
});

const darker_grotesque = Darker_Grotesque({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-darker-grotesque",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito_sans.variable} ${darker_grotesque.variable} h-screen`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
